# (PART\*) Основи {-}

# Що таке програмування? {#programming}

<div class="btn-group" style="width:100%">
  <button style="width:20%; background-color: #ed6a5d">🎥 Лекція</button>
  <button style="width:20%; background-color: #f5be4f">🎙️ Подкаст</button>
  <button style="width:20%; background-color: #61c554">📓 Записник</button>
  <button style="width:20%; background-color: #6db2d6">🤸 Вправи</button>
  <button style="width:20%; background-color: #a38ebd">📝 Шпора</button>
</div>

**⏱️ Час на опанування теми:** 15 хвилин

**🤷 Для чого ми це вивчаємо:**

**🔑 Результати навчання:**

- Розуміння що таке програма, додаток та програмне забезпечення
- Розуміння що таке алгоритм, кодування та програмування 

---

У цій главі ми познайомимось з...

---

## Програма, додаток, програмне забезпечення та код

Давайте почнемо з **програм**. Скоріш за все, перше що ви робите після того як прокинулись -- перевіряєте додатки на ваших телефонах: нові повідомлення в Telegram, прогноз погоди в Weather, пости в Instagram. Й не дивлячись на те, що в повсякденному житті ми називаємо Telegram, Weather та Instagram додатками, в своїй суті вони залишаються програмами.

Давайте з'ясуємо що саме ми маємо на увазі, коли використовуємо слово програмі. Якщо ви зазирнете в Вікіпедію, то ви знайдете щось накшталт "програма -- набір інструкцій для комп'ютра які приводять його у дію для досягнення певної мети". Але це все одно, що сказати що трава зелена: визначення точне, але не дуже корисне для розуміння. 

Щоб швидесенько його зрозуміти, ми розіб'ємо його на частини і почнемо з кінця 🙃. Останню частину, "для досягнення певної мети", ми можемо інтерпретувати як "для вирішення проблеми". Наприклад, додаток Weather дозволяє вам подивитись прогноз погоди в будь-якій точці світу у будь-який час; калькулятор дозвляє швидко підрахувати суму, різницю, добуток або частку. 

Перша частина більш не зрозуміла: "набір інструкцій для комп'ютра". Але тут все просто: "набір інструкцій" -- це те, що комп'ютер повинен зробити. Але головне тут те, що комп'ютер **повинен розуміти що саме він повинен зробити**. Якщо ви будете кричати на електрочайник щоб він закип'ятив воду, то навряд чи він це зробить. А ось якщо ви натиснете кнопку, то ви зможете зробити собі чай. Так само комп'ютер повинен розуміти наші інтрукції або команди. Вони зазвичай написані на спеціальній мові, яка виглядає як дуже дивна англійска -- мова програмування. Комп'ютери розуміють мову програмування. Команди написані на цій мові називаться кодом.

До речі, коли ми кажемо комп'ютер, ми не завжди маємо на увазі саме комп'ютер в повсяденному значенні. Наші смартфони, планшети, ігрові консолі -- теж комп'ютери. Так, вони виглядають трохи інакше і виконують трохи інші функції, але все одно вони виконують програми та мають своє програмне забезпечення. О, а що таке програмне забезпечення? 

Існує три взаємопов'язаних термінів: програма, програмне забезпечення та додаток. Не дивлячись на те, що ми будемо використовувати їх взаємозамінно, давайте все ж таки обговоримо різнцию. Ми казали, що програма -- це сукупність команд або інструкцій. Цей набір команд може бути написанний навіть на листочку. А ось додаток -- це програма, яка використовує графічний інтерфейс користувача (graphical user interface, або скороченно GUI): тобто має намальовані кнопки, поля для вводу, та інші елементи з якими взаємодіє користувач. Ми можемо уявити програми як код написаний зеленими літерами на чорному фоні, а ось додатки -- тим, чим ми користуємось постійно -- Weather, Instagram тощо. Користувач додатків -- це людина, а ось користувач програм може бути інша програма.

Ось вам ще один приклад. Уявіть собі автівку з "голим" кузовом, двигуном та чотирма колесами. Навіть без керма! Досвідчений інженер буде знати як керувати цією "машиною", але це буде дуже складно та некомфортно. Це -- програма. А ось якщо ми додамо кермо, педалі, салон та кондіціонер -- то це вже буде додаток.

Тепер програмне забезпечення. Англійською це звучить звучить як software. В software крім самої програми або декількох програм ми включаємо також документацію та дані, які пов'язані з програмою. Зараз цей термін використовується як сукупність усіх програм пристрою і протиставляється фізичній складовій пристрою. Фізічна складова -- це процесор, оперативна пам'ять та інші мікросхеми, які англійською будуть -- hardware. 

## Програмування, кодування та алгоритми

А тепер ми поговоримо про те, як програми та додатки створюються. Спершу нам треба зрозуміти точну послідовність команд, які нам треба надати комп'ютеру для розв'язання задачі. Це дуже схоже на кулінарний рецепт:

```
- нагрійте пательню
- додайте соняшникової олії
- розбийте два яйця
- посоліть і поперчіть 
- доведіть білок до хрусткої скоринки, але не пересмажте жовток
```

Або на послідовність дій щоб купити шоколадний батончик в автоматі: 

```
- вставте монету
- натисніть номер шоколадного батончику
- натисніть зелену кнопку
- відкрийте нижні дверцята та заберіть батончик 
```

А називати цю послідовність інструкцій ми будемо **алгоритмом**. Але комп'ютер ще не розуміє що саме ми від нього хочемо і нам треба перекласти алгоритм на мову програмування. Цей процес ми будемо називати **кодування**, тобто реалізацєю алгоритма у вигляді програми.

Уявіть що нам треба змусити дрон пролетіти два метри вперед та один метр праворуч. Команди які ми можемо використовувати, це тільки "лети вперед 1 метр" та "лети праворуч 1 метр". Тоді наш алгоритм буде таким:

```
- лети вперед 1 метр
- лети вперед 1 метр
- лети праворуч 1 метр
```

Також у нас є мова програмування з командами `move_forward(100)` та `move_right(100)` -- лети вперед та лети праворуч на один метр. Тоді, якщо ми закодуємо наш алгоритм, отримаємо: 

```
move_forward(100)
move_forward(100)
move_right(100)
```

Вуаля! Ми тільки що створили невеличкий алгоритм та закодували його. До речі, по секрету, це не якась уявна мова програмування та не якись уявний дрон. Це код для дрона RYZE Tello, який був написаний на мові програмування Python. А ось і відео виконання нашого коду:

Ось ми і підійшли до головного питання -- а що ж таке програмування. Відповідь дуже проста: **програмування -- це розробка програми, яка включає в себе і написання алгорітму і безпосередньо кодування**. 

---

У цій главі ми ознайомились з...


<!-- У цій главі ми познайомимось з такими визначеннями, як програма та алгоритм, та розберемося із поняттями програмування та кодування.  -->




<!-- У цій главі ми розберемося з такими поняттями як програмування, кодування, алгоритм та програма. Ці поняття досить широкі та абстрактні, тому ми наведемо велику кількість прикладів.  -->

<!-- ## Що таке комп'ютерна програмне забезпечення, програма та додаток?  -->

<!-- ## Що таке алгоритм, кодування та програмування?  -->



<!-- Якшо ви коли-небудь готували чи спостерігали як хтось готує, вам не складно буде зрозуміти термінологію пов'язану з програмуванням.  -->


<!-- Ви коли-небудь налаштовували будильник чи використовували калькулятор? Якщо так, то у мене для вас є гарні новини -- ви вже програмували в своєму житті. І не важливо що ви використовували фізичний девайс або додаток на телефоні, головне що ви **надавали команди вашому пристрою в певному порядку**. -->



<!-- Алгоритм -- послідовність точних інструкцій, які використовуються для вирішення якоїсь проблеми чи розв'язання задачі. -->

<!-- Код --  послідовність точних інструкція які написанні мовою яку розуміє комп'ютер.  -->

<!-- Кодування -- реалізація алгорітму у вигляді программи, або іншими словами переклад алгоритму на мову, яку розуміють компьютери.  -->

<!-- Програмування -- процес проектування, написання, тестування, зневадження і підтримки комп'ютерних програм. -->

<!-- У вужчому значенні програмування розглядається як кодування — реалізація у вигляді програми одного чи кількох взаємопов'язаних алгоритмів (у сучасних умовах це здійснюється з застосуванням мов програмування). У ширшому сенсі процес програмування охоплює і створення, тобто розробку, алгоритмів, і аналіз потреб майбутніх користувачів програмного забезпечення. -->

<!-- У широкому значенні програмування використовується у значенні створення програми дій або алгоритмів та навчання людей або пристроїв діяти за алгоритмами. -->

<!-- Computer programming is the process of performing a particular computation (or more generally, accomplishing a specific computing result), usually by designing and building an executable computer program. -->


<!-- * Комп'ютерний код пишеться у текстовому редакторі. -->
<!-- Компьютерний код --  -->


<!-- Давайте зробимо крок назад. Все починається не з програмування чи коду, а саме з проблеми, яку треба вирішити. Ви приходите в магазин і вам треба купити два подарунки. Ви невпевнені чи вистачить вам грошей, тому вам треба порахувати суму цін цих подарунки. Якщо ці числа не великі, то ви можете додати їх у голові або навіть порахувати в стовпчик. Проте, рахувати, наприклад в стовпчик не дуже швидко, та й рахувати суму скоріш за все ви будете досить часто. А що до віднімання, множення чи ділення? Ці операції вам теж знадобляться. І десь ось так люди прийшли до того, що їм потрібен калькулятор. -->







<!-- * Кодування  -->
<!-- * Аглоритм  -->
<!-- * Комп'ютера программа або додаток (app) -->
<!-- * мови програмування -->
<!-- * процес який треба автоматизувати -->

<!-- * Код -- це перелік команд у текстовому форматі -->