# Python як мова програмування

<div class="btn-group">
  <button class="lecture">🎥 Лекція</button>
  <button class="podcast">🎙️ Подкаст</button>
  <button class="notebook">📓 Записник</button>
  <button class="exercises">🤸 Вправи</button>
  <button class="cheat">📝 Шпора</button>
</div>

**⏱️ Час на опанування теми:** 15 хвилин

**🤷 Для чого ми це вивчаємо:**

**🔑 Результати навчання:**

- Розуміння які мови програмування існують
- Розуміння чому Python -- найкращя мова програмування для data science, machine learning та artificial intelligence 
- Використання Python як калькулятор

---

Ми почнемо з швидкого огляду галузей розробки програм та подивимось які мови використовються. Далі, ми перелічимо переваги Python та почнемо вже трохи програмувати.

---

## Огляд мов програмування

За деякими оцінками, кількість мов програмування перевищує 7'000. Але ж звісно, що люди активно використовють тільки частину цих мов, тому ми розберемо саме найпопулярніші мови.

Ці мови можна поділити на різні типи використовючи різні критерії: компільовані або інтерпретовані, низькорівневі або високорівнева, тощо. Але ми розділемо мови програмування відповідно до їх призначення та застосування. 

### Game development 

Почнемо з game development або розробка відео-ігор українською. Найкрутішою мовою є C++. Це одна з найшвидших мов програмування. Коли ми кажемо що мова програмування швидка -- ми маємо на увазі, що програми написані на цій мові швидші ніж ідентичні програми написані на інших мовах. До недоліків можна додати, що ця мова досить складна для вивчення. Деякі ігри з серії Grand Theft Auto та World of Warcraft були написані використовючи цю мову. І звичайно ж не забуваємо про Fortnite.  

До речі, програми написані на С++ працюють на різних операційних системах, наприклад на Windows та macOS. і це називається cross-platform, тобто кросс-платформена мова. Усі мови які ми розглянемо, будуть cross-platform.

Далі йде C#. Ця мова трохи повільніша за C++, але набагато простіша для сприйняття. Такі ігри як Call of Duty, Genshin Impact. А ось наприклад Minecraft був написаний на Java. Java може трохи повільніша за C#, але вважається більш популярною.

До речі, ви також можете розробити гру у Python. Порівняно з вищезгаданими мовами, Python вважається повільною мовою. Проте вона набагато легша для вивчення. Ще є вилика ниска більш екзотичних мов, таких як Lua (на якій був розроблений Roblox) та інші.

<!-- Розказати про Unity та Unreal Engines  -->

### Web-development 

Під web developemnt ми маємо на увазі розробку інтернет сайтів. Самою популярною мовою є JavaScript Якщо ви зараз читаєте цю книгу з сайту або дивитесь YouTube відео, то ви вже використовуєте можливості надані мовою JavaScript. Наприклад, навігація для цієї книги (тобто коли ви можете натиснути на главу і вона відкриється) реалізовано за допомогою JavaScript. Або кнопки за допомогою яких ми ставмо на паузу -- це теж JavaScript. 

Ця мова неймовірно потужна і використовується у 98% усіх сайтів. В ці 98% входять усе чим ми користуємось щодня: Google, соціальні мережі Facebook та Twitter, YouTube тощо. JavaScript набагато повільніша за попередні мови, але плюсом є те, що її не дуже складно вивчити.

До речі, ті мови які використовуються для game development, такі як C++, C#, Java, та Python, теж використовються для web development, але для інших цілей ніж JavaScript. 

<!-- Розказати про front-end та back-end  -->

### Mobile app development 

Mobile app development займається розробкою додатків для мобільних пристроїв, таких як смартфонів, планшетів, розумних годинників, тощо. Якщо додаток розробляється для пристроїв Apple (тобто які мають операційну системи iOS) -- то ми використаємо Objective-C чи Swift. А ось якщо пристрій використовує Android -- то розроблятись додаток буде у Java. Ці мови приблизно однакові з точки зору складності, але Objectve-C та Swift трохи швидщі.

<!-- Розказати що так native mobile app? -->

### Data science, machine learning та artificial intelligence 

Якщо нам треба витягти корисні знання з даних чи виконати складне завдання використовючи машине навчання -- то тут є три притенденти: Python, R та Julia. Найшвидша з цих мов -- Julia, але ця мова досить нова, тому не має такої потужної спільноти як Python чи R, та ще вона є більш складною ніж Python чи R.

За складністью Python та R більш-менш однакові і Python трохи швидчий за R. Плюс, Python є набагато поширінішою мовою за R. Тому, не зважаючи на усі недоліки Python порівняно з R, ми будемо вивчати саме її.

### Domain specific languages 

Предметно-орієнтована мова програмування -- це ті мови, які заточені на вирішенні проблеми у вузькій сфері та не призначені для вирішення пробем поза нею. Ось наприклад мова SQL була розроблена для керування базами даних. Проте вона також використовється як допоміжна мова для web development та data science.

### Бібліотеки 

Взагалі кажучи, коли ми кажемо про якусь конкретно мову, ми маємо на увазі не тільки цю мову, але і її бібліотеки, пакети та модулі. Наприклад, коли ми розмовляли про JavaScript, ми також мали на увазі й такі бібліотеки як React, Node.js, Vue та таке інше. Те ж саме стосюється усіх перелічених мов. 


### Summary 

| Мова        | Складність | Використання        | Швидкість |
|-------------|------------|---------------------|-----------|
| С++         | Складна    | Game, Web           | Швидка    |
| C#          | Середня    | Game, Web           | Швидка    |
| Java        | Середня    | Game, Web, Mobile   | Швидка    |
| JavaScript  | Легка      | Web                 | Повільна  |
| Julia       | Середня    | DS/ML/AI            | Швидка    |
| Objective-C | Середня    | Mobile              | Швидка    |
| Python      | Легка      | Game, Web, DS/ML/AI | Повільна  |
| R           | Легка      | DS/ML/AI            | Повільна  |
| Swift       | Середня    | Mobile              | Швидка    |

## Чому Python -- one love?

Вище ми розглянули аж дев'ять різних мов програмування. Чому ми вивчаємо саме Python? Давайте відповімо на ці питання. Почнаємо з того, що чому вивчати Python -- це гарна ідея, навіть якщо вас цікавить щось інше ніж data science/machine learning/artificial intelligenence? 

### Чому вивчати Python -- це гарна ідея? 

Давайте перелічимо усі переваги Python над іншими мовами:

- Легкість у навчанні

  У Python дуже і дуже зрозумілий синтаксис. Синтаксис в програмуванні -- це правила написання коду. Через інтуітивність синтаксису, код на Python легко писати і легко читати. А як наслідок, і вивчати його теж дуже легко. Python також має величезну кількість вбудованих функцій, які вам не треба буде розробляти з нуля.

- Бібліотеки 

  Мабудь найголовніша причина чому ми вибрали саме Python для DS/ML/AI -- це наявність найсучасніших бібліотек. Python, де-факто, є мовою на якій розробляються ключові дослідження у галузі DS/ML/AI. Коли з'являється нова модель, скоріш за все вона буде реалізована саме у Python. Це обумовленно тим, що головні бібліотеки нейроних мереж TensorFlow та PyTorch -- це бібліотеки Python. 

- Продуктивність

  Написати одну і ту саму програму займає набагато меньше часу у Python ніж в інших, більш складних мовах. Також, вона буде займати менше рядків коду. Це важливо, тому що якщо у вас буде помилка в коді -- її легше буде знайти в двох рядках коду ніж в двадцяти.

- Сільнота та допомога

  Python має дуже велику та розвинену громаду користувачів, які охоче допомогають один одному. Якщо у вас не працює код або є якесь запитання -- існує велика ймовірність знайти відповіді в інтернеті, тому що хтось вже мав таке запитання. Якщо ж ні, ви завжди можете запитати на спеціальних платформах, таких як Stackoverflow або GitHub. До речі, ChatGPT теж дуже гарно відповідає на питання стосовно Python. 

- Універсальність

  Як ми вже побачили, Python використовується майже усюди -- game development, web development, artificial intelligence, тощо. Це означає, що якщо ви будуєте дуже складний додаток, наприклад, гру з величезною кількістю artificial intelligence, достатньо знати тільки Python. 

## Починаємо використовувати Python

Однією з цілей цієї книги є навчитись програмувати якомога швидше. Тому не гаємо часу і починаємо програмувати. Так, ми багато чого ще не знаємо, але ж дещо ми все ж таки можемо зробити. Почнемо з того, що нам знадобиться обліковий запис у Google.

Якщо у вас електрона пошта зареєстрована у Google, це означає що у вас вже є обліковий запис. Якщо ж нема -- то його можно дуже швидко створити за наступним посиланням: [https://accounts.google.com/](https://accounts.google.com/). Більш детальний опис ви можете подивитись в Додатку \@ref(google-account). 

Далі треба завітати на сторінку [Google Colab](https://colab.research.google.com/notebooks/welcome.ipynb?hl=uk). Google Colaboratory (або скорочено Colab) дозволяє писати та виконувати код у вашому веб-переглядачі. Для нас це важливий бонус, тому що нам не потрібно витрачати час на встановлення Python на комп'ютер; а ще ми можемо створювати Python програми будь-де, навіть на вашому смартфоні. До речі, якщо ви читаєте цю книгу на комп'ютері, а хочете відкрити Colab записник на іншому девайсі у якого є камера -- ви можете зісканувати QR-код нижче: 

XXX: QR-code for the link

Коли ви відкриєте цю сторінку, те що ви побачите буде виглядати приблизно ось так: 

XXX: screenshot of google colab from different devices (laptop and phone).

На цьому ми не зупиняємось, ще трохи і зможемо писати код. Натискаємо спочатку *Файл* і далі натискаємо **Новий записник**. Це створить новий записник Colab. 

XXX: screenshot of google colab new notebook from different devices (laptop and phone).

Далі все просто. Бачете блимаючий курсор? Ось там і з'виться код якщо ви почнете писати. Ви мабудь думаєте що ви нічого не зможете написати? А ось і не правда -- ми принайні можемо вже використати Python як калькулятор.

Давайте порахуємо скільки тижднів на рік. У невисокосному році 365 днів, а у тиждні 7 днів. Тому ми запишемо: 

```{python, eval = FALSE}
365 / 7
```

І натиснемо коло з трикутником (кнопка **Play**) зліва від коду. Це запустить наш код та порахує `365/7`. Результат розрахунку з'явиться внизу під нашим кодом.

XXX: screenshot of google colab with play button highlighted and calculated 365 / 7 

Вуаля! Ви тільки що написали свій перший код у Python та виконали його і цим варто пишатись. Далі -- тільки вперед! У наступній главі ми розглянемо більш детально записники та функції Google Colab. 

---

У цій главі ми подивились на різні мови програмування та де їх використовують. Також, ми відповіли на питання чому ми вивчаємо саме Python, а не будь яку іншу мову. Напослідок, ми створили свій перший записник у Google Colab, написали перший рядок коду та виконали його. 

