# Google Colaboratory: програмуй у своєму вебпереглядачі

<div class="btn-group">
  <button class="lecture">🎥 Лекція</button>
  <button class="podcast">🎙️ Подкаст</button>
  <button class="notebook">📓 Записник</button>
  <button class="exercises">🤸 Вправи</button>
  <button class="cheat">📝 Шпора</button>
</div>

**⏱️ Час на опанування теми:** 15 хвилин

**🤷 Для чого ми це вивчаємо:**

- вільно та впевнено володіти основними функціями Goolge Colaboratory
- мати можливість швидко експериментувати з кодом
- мати можливість не фокусуватись на незначних деталях середовища розробки

**🔑 Результати навчання:**

- Створювати, зберігати, відкривати та перейменовувати записники Colab
- Вставляти та видаляти клітинки з кодом та текстом
- Виконувати клітину з кодом 

---

В попередній главі ми створили перший записник Colab. Тепер нам треба закріпити цю навичку та додати нові: зберегти, відкрити та перейменувати записники Colab. Потім ми навчимося працювати з клітинками -- виконувати та додавати нові. Опанування декількох навичок ми залишили у вигляді вправ. 

---

## ✍️ Розбираємось де пишеться код

У главі \@ref(programming) ми розглянули код, як перелік команд написаний певною мовою програмування. Зазвичай код зберігається у текстових файлах, які називаються <span class="highlight-container"><span class="highlight">скрипти<span class="tooltiptext">🇬🇧 scripts</span></span></span>^[Насправді вони можуть називатись або скриптами або файлами з початковим кодом, залежно від того, чи мова програмування компільована, чи інтерпретована. Python -- інтерпретована мова, то ми будемо називати ці файли скриптами.]. Ці файли мають розширення відповідно до мови програмування на якій цей код написаний. Наприклад, код написаний у Python зберігається у файлах з розширенням `.py`.

 <!-- XXX: screen of a pure source file  -->

З іншого боку, в рамках 📈 Data Science, 🤖 Machine Learning та 🧠 Artificial Intelligence нас буде цікавити не сам код, а його результати. Коли ми будемо аналізувати дані, нам будуть важливі висновки, які ми зробимо, наприклад, з графіку який побудує код. Звичайно ми можемо записати ці висновки в окремому файли, але набагато зручніше тримати поряд і код, який генерує графік, і сам графік, і висновки у текстовій формі. Такі міркування привели до створення так званих інтерактивних записників. Такі записники містять в собі код, результати коду (наприклад таблиці чи графіки) та текст який описує ці результати. Ми будемо працювати із записниками, які зберігаються у форматі `.ipynb`^[Це не єдиний формат інтерактивних записників. Також існують Quarto документи та їх предки -- документи R Markdown.].

<!-- XXX: screen of a notebook  -->

Код пишеться (або як правильно говорити -- розробляється) в спеціальних текстових редакторах, які називаються <span class="highlight-container"><span class="highlight">інтегрованими середовищами розробки<span class="tooltiptext">🇬🇧 Integrated development environment, або скорочено IDE</span></span></span>. Ми можемо собі уявити такі середовища як редактор Microsoft Word, але тільки для коду. Найпопулярнішими з них є Visual Studio Code, PyCharm та JupyterLab. Зазвичай інтегровані середовища розробки встановлюються на вашому комп'ютері та працюють локально. 

Але ми пропонуємо трохи інший шлях -- використовувати Colab. Це таке ж саме середовище розробки, але воно хмарне. Тобто вам не потрібно нічого встановлювати і ви можете працювати зі свого вебпереглядача (такого як Chorme, Safari, Firefox тощо). Найголовніше зараз -- це почати якнайшвидше програмувати, ніж гаяти час на встановлення Python та текстових редакторів. Тим паче якщо ми використовуємо Colab, то ви можете кодити з будь-якого пристрою, якщо у нього є вебпереглядач.

<!-- XXX: scheme of ide's local vs cloud  -->

Давайте тепер здобудемо практичні навички праці з Colab. Необхідно розуміти, що просто прочитавши цю главу вам буде важко закріпити ці навички на рівні рефлексів. Тому дуже важливо зробити вправи, посилання на які ви знайдете на початку цієї глави.

## 📓 Створюємо, зберігаємо, відкриваємо та перейменовуємо записники Colab

Перед тим як ми почнемо, треба зазначити що Colab записники можуть мати або світлу або темну тему, залежно від налаштувань вашого комп'ютера. Усі дії, які ми розглянемо однакові, незалежно від того яка тема у вас використовується.

<!-- XXX: light vs dark theme  -->

Перше що ми навчились вже робити у попередній главі -- це створювати записники. Треба спочатку натиснути **Файл**, а потім **Новий записник**. Ці відкриє нову вкладку в вашому браузері з новим чистим записником. 

<!-- XXX: highlighted parts  -->

Коли ви запишете якийсь код або текст, вам треба буде зберегти цей записник. Для цього натискаємо **Файл**, а потім **Зберегти**.

<!-- XXX: highlighted parts  -->

Colab записник досить розумна штука, тому він час від часу буде зберігати ваш записник автоматично. 

Якщо ви хочете відкрити записник, який ви до цього зберегли, то вам треба натиснути **Файл**, потім **Відкрити записник**, і вибрати той записник, який вам потрібен: 

<!-- XXX: highlighted parts  -->

І звичайно ж ми захочемо замінити назву за замовчуванням на більш зрозуміле ім'я. Для цього вибираємо **Файл** і в випадаючому меню **Перейменувати**. Тоді ви можете задати нове ім'я в лівому верхньому куті. 

<!-- XXX: highlighted parts  -->

Або ви можете два рази клацнути на ім'я записника і тоді змінити його. 

## 🔬 Працюємо з клітинками

Записник Colab складається з **клітинок** -- це такі собі невеличкі блоки які розташовані один під одним. Ці клітинки можуть містити в собі код або текст.

Клітинки для коду будуть трохи темніші за загальний фон записника. Вони також будуть починатись з квадратних дужок, між якими може бути число. Також коли ви будете на них наводити, ви побачите кнопку **Play** (тобто трикутничок в кружечку). 

<!-- XXX: code cell  -->


Коли ви натиснете на кнопку **Play** -- ви виконаєте код у цій клітинці. Якщо цей код повинен щось вивести на екран, наприклад суму двох чисел або графік, то це з'явиться під цією клітиною. Якщо код виконався без помилок, ви побачите: (1) зелену галочку, яка інформує, що код успішно виконався та (2) кількість секунд за які виконався код. А ось якщо код містив помилку, то замість результату коду ви побачите текстовий опис помилки та малесенький червоний знак оклику замість зеленої галочки. 

У Python до речі дуже порядок виконання коду дуже важливий. Тому після того, як ви виконали код у клітинці й натиснете на іншій клітинці, то між квадратними дужками виконаної клітинки побачите порядковий номер виконання. 

<!-- XXX: code cell after it has been run  -->

В клітинках з текстом все трохи простіше. Їх не треба виконувати, і ви можете змінити їх вміст, якщо натиснете на них два рази. Такі клітини містять текст в спеціальному форматі, який називається Markdown. Без паніки -- нам не треба його зараз вивчати! Тим паче що просто написаний текст буде відображатися як є у цих клітинках. Якщо вам цікаво -- ви можете прочитати про цей формат у Додатку \@ref(markdown), але і без нього ви впораєтесь без проблем. 

<!-- XXX: example of text cell -->

Є три способи додати нову клітину: 

- Натиснути __Вставити__ і потім вибрати в випадаючому меню або __Клітинка з кодом__ або __Клітинка з текстом__
- Натиснути кнопки __+ Код__ або __+ Текст__ під меню
- Навести курсор на нижню частину вибраної клітинки і натиснути __+ Код__ або __+ Текст__

<!-- XXX: example of text cell -->

Якщо ви натиснете курсором на клітинку, то праворуч з'являться кнопки з опціями. Ці опції ми ретельно роздивимось та опануємо у вправах.

---

В цій главі ми навчились працювати у записниках Colab. Почали зі створення записників і потім перейшли до роботи з клітинками, які є основною складовою записників.
