# Змінні, функції та оператори {#vars}

<div class="btn-group">
  <button class="lecture">🎥 Лекція</button>
  <button class="podcast">🎙️ Подкаст</button>
  <button class="notebook">📓 Записник</button>
  <button class="exercises">🤸 Вправи</button>
  <button class="cheat">📝 Шпора</button>
</div>

**⏱️ Час на опанування теми:** 15 хвилин

**🤷 Для чого ми це вивчаємо:**

**🔑 Результати навчання:**

- Створювати змінні
- Використовувати та змінювати занчення змінних
- Викликати функцію та зазначати аргументи
- Використовувати математичні оператори

---

Найпершим концептом в програмуванні який нам доведеться вивчити, буде змінні. Ми навчимося створювати нові змінні, використовувати та змінювати їх значення. Далі, ми перейдемо до фунцкій і навчимося їх викликати. В кінці цієї глави, ми познайомимось з деякими математичними операторами.

---

## Змінні

Зараз ми почнемо будувати наші навички з програмування. Філософія наша буде проста -- ми будемо використовувати те, що ми вже знаємо, і по цеглині додавати нові знання. Якщо ви хочете прискорити цей процес в кілька разів, наполегливо рекомендується відкрити новий записник та кодувати паралельно із книгою. Почнемо ми зі змінних.

Скажімо, у вашому смартфоні збережено дуже велика кількість фотографій і залишилось 5.5 Gb (гігабайт) пам'яті з 64 Gb доступних. Спочатку, давайте з'ясуємо скільки вільного місця залишилось в мегабайтах. Нагадаємо, що в одному гігабайті міститься 1000 мегабайт. Ми вже вміємо використовувати Python як калькулятор, то ж давайте порахуємо:

```{python}
5.5 * 1000
```

Тепер нам цікаво скільки фотографій ще ми можемо зробити. Одна фотографія на вашому смартфоні займає приблизно 3 Mb (мегабайт). Нам треба перевести 5.5 Gb на мегабайти, тобто `5.5 * 1000` і розділити на розмір фотографії, тобто 3 Mb. 

```{python}
5.5 * 1000 / 3
```

А тепер ми розрахуємо який відсоток вашої загальної пам'яті залишається доступним. Для цього ділимо кількість вільної пам'яті (5.5 Gb) на 64 Gb і множимо на 100%: 

```{python}
5.5 / 64 * 100
```

Через кілька днів ваша пам'ять зменшилась до `5` Gb і ми хочемо порахувати усе те, що ми рахували до цього: (1) кількість вільної пам'яті у Mb, (2) приблизна кількість фотографій і (3) відсоток вільної пам'яті:

```{python}
5 * 1000
```

```{python}
5 * 1000 / 3
```

```{python}
5 / 64 * 100
```

Так само, через кілька днів, пам'ять зменшується до `4.5` і нам треба порахувати ще разочок: 

```{python}
4.5 * 1000
```

```{python}
5.5 * 1000 / 3
```

```{python}
4.5 / 64 * 100
```

Якщо ви уважно дивились на цифри, то звернули увагу на те, що кількість фотографій збільшилась. Як таке можливо? Якщо ми придивимось, ми побачемо що ми наплутали та зазначили 5.5 замість 4.5. Насправді, ми зробили цю помилку не випадково. Ми використовували и переписували одне і те саме число (кількість вільної пам'яті у Gb) тричі, і тому вирогідність зробити помилку хоча б в одному місці дуже велика.

Саме цей факт і є мотивацією нового концепту який називається змінна. Формально, **змінна** -- це **ім'я**, яке вказує на певний об'єкт (тобто ділянку пам'яті комп'ютера). У цій главі ми будемо працювати з найпростішими змінними які будуть вказувати на числові значення. Ми можемо створювати нові змінні, змінювати їх значення, але найважливіше -- використовувати значення змінних у коді. 

Давайте створемо нову змінну з ім'ям `free_space` (з англійскої -- вільне місце) і присвоємо цій змінній значення `4.5`:

```{python}
free_space = 4.5
```

Синтаксис створення змінних простий і складаєтся з трьох частин: `ім'я` змінної зліва, потім `знак дорівнює`, а все що залишається праворуч -- це буде `значення`.

<!-- XXX: scheme of syntax of math operators -->

Спочатку, давайте подивимось що саме міститься в змінній `free_space`. Для цього ми можемо просто зазначити її ім'я в клітинці для коду та виконати її:

```{python}
free_space
```

Окей, їдемо далі. Коли змінна створена, ми можемо використовувати її в наших розрахунках. Давайте порахуємо кількість вільної пам'яті в мегабайтах:

```{python}
free_space * 1000
```

Тепер кількість фотографій, які ми можемо зробити:

```{python}
free_space * 1000 / 3
```

І кількість вільної пам'яті в процентах:

```{python}
free_space / 64 * 100
```

А тепер ми змінемо значення змінної на `4` Gb і знову запустимо розрахунки. Тут важливо звернути увагу, що результати розрахунків використовуються нове значення `4`:

```{python}
free_space = 4
```

Давайте спочатку перевіримо, що `free_space` все ж таки містить значення `4`:

```{python}
free_space
```

Кількість вільної пам'яті у мегабайтах зміниться на:

```{python}
free_space * 1000
```

Кількість фотографій, коли у нас `4` Gb вільної пам'ті буде:

```{python}
free_space * 1000 / 3
```

А вільна пам'ять в процентах:

```{python}
free_space / 64 * 100
```

## Функції

Кількість вільної пам'яті в 4 Gb відповідає 6.25% від усієї доступної пам'яті телефона (дивись попередні розрахунки). Звичайно десяткова частина 0.25% цього відсотка для нас не так суттєва. Ми все одно округляємо в голові до 6%, коли дивимось. Але ми не повинні цього робити в голові -- у Python існує механізм, який дозволяє комп'ютерові округлити це число. Цей механізм -- фунцкія `round()`: 

```{python}
round(6.25)
```

Згодом ви побачите, що у програмуванні ми дуже часто виконуємо одні і ті самі завдання. Наприклад, завдання знайти максимальне значення серед чисел або знайти модуль числа виникають майже постійно. І щоб щоразу не писати код, який вирішує такі повторні завдання, ми можемо загорнути його у самостійну невеличку програму, яку ми назвемо **функцієй**. Зазвичай у функцій є ім'я за яким ми можемо її викликати -- тобто виконати. Після імені фунцкції треба написати дужки, між якими ми можемо зазначити аргументи (якщо це передбачає функція).

<!-- XXX: syntax of function call -->

До речі, аргументами функції можуть бути не тільки значення, а й змінні, вирази та виклики інших функцій. Повертаючись до прикладу про вільну пам'ять, ми можемо використати вираз `free_space / 64 * 100` безпосередньо як аргумент до фунцкції (ми розберемося що таке вирази за хвилину у секції \@ref(operators)):

```{python}
round(free_space / 64 * 100)
```

А ще ми можемо записати значення, яке поверне функція до змінної: 

```{python}
free_space_percentage = round(free_space / 64 * 100)
```

І потім використати, наприклад для того, щоб порахувати кількість зайнятої пам'ті: 

```{python}
100 - free_space_percentage
```

Ось приклад функції `max()`, яка повертає максимум серед зазначенних чисел:

```{python}
max(3, 3.5, 10, -20)
```

А ось приклад функції `abs()`, яка знаходить модуль числа: 

```{python}
abs(-10)
```


## Оператори {#operators}

Оператори -- це спеціальні символи (наприклад, `*`, `/` тощо), які використовуються для операцій. Так, згода, це все одно, що сказата що вода мокра. Гарна новина у тому, що ми вже знайомі із дуже важливою частиною з них -- математичні оператори. Вони збігаються з математичними символами:

* `+` -- додавання
* `-` -- віднімання
* `*` -- множення
* `/` -- ділення

Це не все. Ще до математичних операторів відносять також: піднесення до степіню (`**`) та отримання неповної частки (`//`) та остачи (`%`) від ділення. Якщо бути відвертим, то останні два оператори використовуються дуже і дуже рідко. Тому, якщо ви не пам'ятаєте що це таке не повна частка та остача -- не біда.

Розглянемо множення двох чисел з нашого прикладу `free_space * 1000`. Змінні, значення та вирази, на які ми застосовуємо оператор, називаються **операндами**.  Тобто у випадку математичних операторів, операндами є все що стоїть ліворуч та стоїть праворуч від опрератора.

У математчних операторів дуже інтуітивний синтаксис, який поділяється на три частини: перший операнд, беспосередньо сам оператор і другий операнд.

<!-- XXX: scheme of syntax of math operators -->

Послідовність з операндів та операторів називається виразом. Наприклад, `2 + 2` є виразом, і наприклад `free_space / 64 * 100` є складним, але все одно виразом.

Ми вже бачили багато прикладів з операторами, коли робили наші підрахунки. Тут ми тільки глянемо на новий оператор піднесення до степіню:

```{python}
3 ** 2
```

Крім математичних операторів існують ще інші, як наприклад, оператори порівняння, логічні оператори тощо. Ми до них повернемось у Главі \@ref(ifelse).

До речі, у виразах із операторами, дужки відіграють таку ж роль, як і в математиці -- вони регулюють порядок виконання дій. Наприклад, вирази `2 + 3 * 4` буде мати зовсім інший результат ніж `(2 + 3) * 4`:

```{python}
2 + 3 * 4
```

```{python}
(2 + 3) * 4
```

<!-- Подумай, може є сенс поміняти місцями оператори та функції, тоді вирішиться проблема з виразами -->
<!-- Подумай, може є сенс додати про методи???-->

---

У цій главі ми дізнались для чого нам потрібні змінні і як з ними працювати. Більш того, ми навчились викликати функції та користуватись деякими операторами.
