# Синтаксис

<div class="btn-group">
  <button class="lecture">🎥 Лекція</button>
  <button class="podcast">🎙️ Подкаст</button>
  <button class="notebook">📓 Записник</button>
  <button class="exercises">🤸 Вправи</button>
  <button class="cheat">📝 Шпора</button>
</div>

**⏱️ Час на опанування теми:** 15 хвилин

**🤷 Для чого ми це вивчаємо:**

- розуміти правила написання коду у Python
- уникати тривіальних помилок пов'язаних з неправильно написаним кодом

**🔑 Результати навчання:**

- правильно розміщувати інструкції
- правильно розставляти пробіли
- коментувати код
- називати змінні

---

Синтаксис -- це правила за якими ми пишемо код. І у цій главі ми покажемо тільки кілька найважливіших правил. Звичайно, ми не будемо зазначати усі можливі, тому що вивчати правило має сенс тільки коли воно знадобиться.

## ✍️ Розміщуємо інструкції на окремих рядках

Під інструкцією ми будемо розуміти синтаксичну одиницю яка виражає певну дію. Наприклад, коли ми створюємо нову змінну або присвоюємо нове значення вважається однією інструкцією. Також інструкцією є будь-який вираз, який може містити в собі виклик функцій та використання операторів. Тобто все що ми робили до цього є інструкціями. 

<!-- XXX: example of the script  -->

У Python зазвичай кожну інструкцію ми пишемо в окремому рядку. Наприклад:

```{python}
grade = 9
(grade - 1) / 11 * 100
```

У Python інструкції можна також записати в один рядок і відокремити крапкою з комою (`;`), але це вважається ознакою поганого стилю, тому що код в таких випадках складніше зрозуміти. 

Python буде ігнорувати пусті рядки. Наприклад, попередній код є еквівалентним наступному коду. Зверніть увагу, що нижче приведений код має два пусті рядки:

```{python}
grade = 9


(grade - 1) / 11 * 100
```

Такі пусті рядки ми будемо використовувати для того, щоб відділити частини коду, щоб покращити читабельність Про це ми поговоримо детальніше в Додатку \@ref(style). 

До речі, в одній клітинці записника Colab може міститись скільки завгодно інструкцій. Якщо остання інструкція -- це вираз який повертає значення -- це значення буде надруковано під клітинкою, коли ми її виконаємо: 

```{python, eval = FALSE}
temp_c = 23
temp_c
temp_c * 9 / 2 + 32
```

```{python, eval = TRUE, echo = FALSE}
temp_c = 23
temp_c * 9 / 2 + 32
```

У попередньому випадку, значення `temp_c` не було надруковано, тому що це не була остання інструкція. Якщо ж ми хочемо надрукувати значення виразу чи змінної десь в середині клітинки, ми можемо використати функцію `print()`: 

```{python, eval = FALSE}
temp_c = 23
print(temp_c)
temp_c * 9 / 2 + 32
```

```{python, echo = FALSE}
temp_c = 23
print(temp_c)
temp_c * 9 / 2 + 32
```

Кількість інструкцій в одній клітинці -- це про стиль написання коду, про який ми поговоримо у Додатку \@ref(style).

## 🫙 Ставимо пробіли

Зазвичай, Python буде ігнорувати пробіли у коді. Наприклад, інструкція `x = 1` та `x=1` має одне і те саме значення для Python. Так само як і наступний виклик функції `sum(x)` та `sum (x)` -- інтерпретуватимуться Python однаково. Проте для нас це буде важливо, тому що буде впливати на читабельність коду, і про це ми поговоримо більш детально у Додатку \@ref(style).

## 📬 Використовуємо коментарі

Для того, щоб код зробити більш зрозумілим, ми будемо часто писати коментарі в коді. Коментарі пояснюють для чого ми написали ті чи інші інструкції. Щоб додати коментар у Python, треба почати рядок тексту із символу `#`. Все що буде написано праворуч від такого символу буде ігноруватись, тобто не сприйматись як код:

```{python}
# Рахуємо скільки секунд в одній добі. Цей коментар не буде сприматись як код.
60 * 60 * 24
```

Ми навіть можемо писати коментар в тому ж рядку що й інструкція, почавши його з `#`: 

```{python}
grade = 12 # оцінка з фізики
```

Також, нам буде дуже зручно **закоментувати** код, наприклад, коли ми будемо експериментувати. У зазначеному внизу випадку, рядок `grade = 11` не буде виконаний, тому що починається з `#`. Тому наш код поверне `12` замість `11`:

```{python}
grade = 12 
# grade = 11
grade
```

Не забувайте подивитись вправи, щоб повністю опанувати коментарі. Вам може здатись, що ваші програми ніхто не буде бачити. Проте буде один, але дуже важливий читач -- майбутній ви. І повірте, майбутній-ви буде дуже вдячний за коментарі. 

## 🪪 Називаємо змінні

У Python імена складаються з символів [Юнікоду](https://uk.wikipedia.org/wiki/Юнікод), але ми будемо використовувати тільки латинську абетку. Простими словами, для імен змінних ми будемо використовувати літери з англійської мови.

Ми можемо надати змінній будь-яке ім'я і існує всього лише декілька правил:

- ім'я повинно починатись або з малої чи великої літери або з підкреслення (`_`)

  ```{python}
  # допустимі імена
  _rock_ = 0.5
  paper = 10
  Sissors = 2
  ```

- ім'я не може починатись із цифри
  
  ```{python, eval = FALSE}
  # недопустимі імена
  10pen = 10
  ```
  
- ім'я повинно складатись із цифр, літер (малих та великих) та підкреслення (`_`)

  ```{python, eval = FALSE}
  # допустимі імена
  long_name_with_numbers_42 = 10
  a_ = 24
  CamelCase = 345
  VAR = 3
  
  # недопустимі імена
  a b = 30
  dog-cat = 1
  ```
  
- імена змінних чутливі до регістру

  ```{python, eval = FALSE}
  # ці змінні різні
  dog = 1
  DOG = 2
  ```
  
Ще одне неформальне правило, якого ми будемо притримуватись -- не давати імена змінним, які вже зарезервовано для вбудованих функцій. Наприклад, це погана ідея використовувати такі імена як `round`, `max` тощо.

---

У цій главі ми вивчили кілька важливих правил щодо написання коду у Python. Почали ми з інструкцій, які повинні бути зазначені на окремих рядках, далі ми розглянули використання пробілів. Ми також навчилися користуватися коментарями та називати змінні згідно з правил Python. 
