# (PART\*) Типи та структури даних {-}

# Типи скалярних даних

<div class="btn-group">
  <button class="lecture">🎥 Лекція</button>
  <button class="podcast">🎙️ Подкаст</button>
  <button class="notebook">📓 Записник</button>
  <button class="exercises">🤸 Вправи</button>
  <button class="cheat">📝 Шпора</button>
</div>

**⏱️ Час на опанування теми:** 15 хвилин

**🤷 Для чого ми це вивчаємо:**

**🔑 Результати навчання:**

- Розуміння що таке програма, додаток та програмне забезпечення
- Розуміння що таке алгоритм, кодування та програмування 

---

Ми розглянемо тільки ті типи даних, які активно використовуються в data science, machine learning та artificial intelligence.

---

У попередніх главах, ми створювали змінні, які вказували на об'єкти з одним єдиним значенням. Такі об'єкти ми будемо називати скалярами. До сих пір, ми розглядали скаляри, які містили тільки числові значення. Цим типом скаляри не обмежуються. Ми можемо також створити скаляри, які будуть містити текстові (наприклад: `I love machine learning`, `apple`) та бульові значення (наприклад, `True` та `False`).

Ми розберемо чотири найважливіші типи скалярів:

- `int`: тип даних для цілих чисел
- `float`: тип даних для дійсних чисел
- `bool`: тип даних для бульових значень
- `str`: тип даних для текстових рядків

Існують ще більш екзотичні, такі як `complex`, `bytes`, `NoneType`, але вони зараз нам не знадобляться. До одного з них ми повернемось у наступних главах, коли вони будуть використовуватись. А зараз почнемо ми саме з того, що ми вже бачили -- чисел, які представлені у Python типом даних `int` та `float`.

## 🔢 Використовуємо тип `int` для цілих чисел

Цілі числа -- це ті числа, які не мають дробової частини^[Це звичайно дуже кепське визначення, проте дуже зрозуміле]. Наприклад: `0`, `-112342345`, `25` тощо. Для цього ми будемо використовувати тип даних `int`^[`int` -- це скорочення від integer, яке з англійскої перекладається як ціле число]: 

Якщо ж ми хочемо зазначити від'ємне число, то нам треба поставити знак `-` на початку нашого числа: 

```{python}
n_jumps = 44
n_jumps
```

Наприклад, значення `int` підходять для того, щоб утримувати кількість стрибків з парашутом, кількості колес в автомобілі тощо. 

## ⛵️ Використовуємо тип `float` для дійсних чисел

Якщо ж число має дробову частину, то ми його можемо представити за допомогою типу `float`. У Python задля десяткового розділювача використовується крапка `.` замість звичною для нас коми `,`. Іншими словами, число `3,7` буде представленно як `3.7`. Увага: використання пробілу до або після десяткової крапки викличе помилку! 

Створюати скаляри типу `float` лекго:

```{python}
ugly_number = 2.913485143
ugly_number
```

Наприклад, ми можемо зберігати температуру пацієнта `36.6` або ціну `23.99` в об'єкті, яка має тип `float`. До речі, ми можемо також зберігати й цілі числа. Для цього ми поставимо крапку і нуль після цілої частини:

```{python}
nice_number = 25.0
nice_number
```

## 🐂 Використовуємо тип `bool` для бульових значень

Об'єкти типу `bool` можуть приймати два значення: або `True` або `False`. З англійської, `True` -- істина, `False` - хибність. Ми використовуємо цей тип скалярів для даних, які можуть приняти тільки два значення. Наприклад -- телевізор може бути увімкненим або вимкненим. Зараз може бути або день або ніч. Літак може прилитіти вчасно або запізнитись. Давайте створимо нову змінну з ім'ям `is_delayed`: 

```{python}
is_delayed = True
is_delayed
```

До речі, не забувайте що Python чутливий до регістру, тобто він відрізняє великі та малі літери. Тому писати `True` і `False` треба писати саме як вони написані: перша велика і всі інші малі літери.

## 🔤 Використовуємо тип `str` для текстових стрічок 

Також нам знадобиться спеціальний скаляр для зберігання тексту. Такі значення ми будемо називати текстові стрічки або просто стрічки^[Англійською string. Деякі книги використовують поняття **рядки**, але тоді нам буде важко розрізняти a row of a table та a line of a text.]. Під текстовою стрічкою ми розумімо послідовність символів. Наприклад, ось це `Hey! I am a string!` -- стрічка. Python підтримує усі символи з Юнікоду, тому стрічка може бути написана українською `Я є стрічка`.

Щоб створити стрічку, нам треба загорнути текст цієї стрічки у подвійні (`"`) чи одинарні (`'`) лапки. Давайте створимо стрічку за допомогою подвійних лапок:

```{python}
greetings_en = "Hello!" # подвійні лапки
greetings_en
```

А тепер за допомогою одинарних лапок:

```{python}
greetings_ua = 'Вітання!' # одинарні лапки
greetings_ua
```

Стрічки -- дуже важливі об'єкти і ми можемо робити з ними велу кількість корисного. Проте зараз для нас набагато важливіше побудувати загальне розуміння програмування. Тому ми залишимо більше практичної інформації у Додатку \@ref(string).

## 🪄 Перетворюємо типи

Одна і та сама інформація може зберігатись в об'єктах різних типів. Наприклад, число `2008` (рік нарождення) може зебрігатись в об'єкті типу `int`, `float` або `str`. Давайте представимо `2008` за допомогою об'єкта `str`

```{python}
year_str = "2008" # нагадуємо, що str створюється за допомогою лапок
year_str
```

Існує дуже корисна функція, яка дозволяє перевірити тип об'єкта. Називається вона `type()`:

```{python}
type(year_str)
```

Головну інформацію, яку нам треба побачити, це -- `str`. Усе інше, тобто `<class ' '>` ми можемо наразі проігнорувати. Якщо ж наш рік `2008` буде представлений об'єктом `float`, то фунцкія поверне `<class 'float'>`:

```{python}
year_float = 2008.0 # нагадуємо, що float створюється за домомогою крапки
type(year_float)
```

Залежно від типу даних, об'єкт буде себе поводитись різним чином. Наприклад, `int` та `float` без проблем можна використовувати в одному виразі:

```{python}
year_float = 2008.0
current_year = 2023 # цей об'єкт має тип int
current_year - year_float
```

А ось якщо наш рік представлений об'єктом `str`, це означає що ми не можемо поводитись з ним, як з числом. Навіть якщо воно виглядає як число. Давайте подивимось, що трапиться, якщо ми відімимо рік народження, який зберігається в `str`, від числа `2023`:

```{python, error = TRUE}
year_str = "2008" 
2023 - year_str
```

Упс, щось пішло не так. Виявляється ми не можемо віднімати об'єкти з даними `int` та `str`. Але що нам робити, якщо нам все одно треба відняти ці числа? Виявляється, ми можемо перетворювати об'єкти одного типу на інший. Для цього ми будемо використовувати функції: 

- `int()` для перетворення на об'єкт `int`
- `float()` для перетворення на об'єкт `int`
- `str()` для перетворення на об'єкт `str`

Давайте спробуємо перетворити `year_str` на об'єкт типу `int`: 

```{python}
year_str = "2008"
year_int = int(year_str)
type(year_int)
```

Тепер ми можемо використати `year_int`, яка була створена з `year_str`, щоб порахувати вік: 

```{python}
2023 - year_int
```

Те що треба! Але будьте обережні, не завжди ми можемо перести `str` до `int` або `float`. Наприклад, перевести текстові символи, а не цифрові, ми не можемо, тому що це не має математичного сенсу:

```{python, error = TRUE}
some_letters = "number"
int(some_letters)
```

У вправах, ми познайомимось із перетворенням об'єктів типу `boolean` на інші типи, та навпаки.

---

