# Списки `list` {#list}

<!-- Може краще назвати контейнери чи коллекції -->
<!-- Мабудь ні, тому що тоді доведеться додавати сюди str -->

<div class="btn-group" style="width:100%">
  <button style="width:20%; background-color: #ed6a5d">🎥 Лекція</button>
  <button style="width:20%; background-color: #f5be4f">🎙️ Подкаст</button>
  <button style="width:20%; background-color: #61c554">📓 Записник</button>
  <button style="width:20%; background-color: #6db2d6">🤸 Вправи</button>
  <button style="width:20%; background-color: #a38ebd">📝 Шпора</button>
</div>

**⏱️ Час на опанування теми:** 15 хвилин

**🤷 Для чого ми це вивчаємо:**

**🔑 Результати навчання:**

- Розуміння що таке програма, додаток та програмне забезпечення
- Розуміння що таке алгоритм, кодування та програмування 

---

У цій главі, ми будемо вивчати чи не найважливіший контейнер. Він дуже універсальний та зручний.

---

Ви пам'ятаєте хто входив у склад Guardians of the Galaxy (Вартові Галактики)? Це були Star-Lord, Gamora, Drax, Rocket та Groot. Ми вже знаємо як створювати змінні текстових стрічок `str`, і якщо нам знадобиться використати імена героїв у коді, ми можемо створити окремі змінні для кожного з них: 

```{python}
guardian1 = "Star Lord"
guardian2 = "Gamora"
guardian3 = "Drax"
guardian4 = "Rocket"
guardian5 = "Groot"
```

Якщо нам треба буде вивести на екран імена усіх вартових, то нам потрібно буде прописати кожну змінну: 
```{python}
print(guardian1)
print(guardian2)
print(guardian3)
print(guardian3)
print(guardian5)
```

Це не дуже зручно, тим паче що ми зробили помилку і два рази вивели Drax замість Rocket. Тобто ми написали другий раз `print(guardian3)`, замість `print(guardian4)`. Ракеті це точно б не сподобалось. А уявіть скільки треба буде писати, коли до вартових ще приєднати Yondu, Mantis, Nebula, Thor та Kraglin Obfonteri? Це вже десять членів, і нам треба буде писати щоразу десять рядків коду, якщо захочемо вивести їх імена на екран. 

На щястя, у Python існує тип об'єкту, який називається `list`, або українською **список**. Під списком ми розуміємо впорядковану послідовність якихось об'єктів, які ми будемо називати елементами. Простими словами, список -- це ланцюжок із елементів. Такі елементи можуть бути будь чим -- числами `int`, стрічками `int` або навіть іншими списками `list`. І також `list` дозволяє зберігати скільки завгодно однакових елементів.

<!-- XXX: draw a diagram of a list-->

Списки `list` можуть мати будь яку довжину. Ми зможемо змінювати їх елементи, додавати та видаляти елементи. Для нас буде дуже важливий порядок цих елементів, тому що доступ до елементів реалізований через їх порядковий номер.

Використовуються списки вони зазвичай для переліків та списків. Наприклад, імена членів вашої родини, називи країн які входять до Європейського союзу, роки випуску платівок The Beatles, ваш to-do список на сьогодні тощо. З іншого боку, нас ніхто не обмежує додати до списку будь-яку не повязану між собою інформацію.

## Створюємо `list`

Найпростіший спосіб створення `list` -- це прописати його елементи через кому `,` і "загорнути" у квадратні дужки `[` та `]`. Давайте створемо новий `list` з ім'ям `guardians`: 

```{python}
guardians = ["Star Lord", "Gamora", "Drax", "Rocket", "Groot"]
```

<!-- XXX: draw a diagram of creating a list-->

Тепер нам буде набагато простіше вивести імена на екран: 

```{python}
guardians
```

Не забувайте, що ми також можемо замість конкретних значень зазначити також змінні або вирази: 

```{python}
guardians = [guardian1, guardian2, guardian3, guardian4, guardian5]
```

Давайте ще створимо `list`, який буде містити абсолютно довільні значення:

```{python} 
star_lord = ["Peter Jason Quill", 1976, 2023 - 1976, 1.88, True]
star_lord
```

Список `star_lord` містить елемент типу `str` зі значенням `"Peter Jason Quill"`, елемент типу `int` зі значенням `1976`, вираз `2023 - 1976` який поверне об'єкт з типом `int`, елемент типу `float` зі значенням `1.88` та елемент типу `bool` зі значенням `True`.

А ще ми казали, що елементами списків, можуть бути інші списки. Давайте створимо список, перший елемент якого буде також список: 

```{python}
gamora = [["Gamora", "Zen", "Whoberi", "Ben", "Titan"], 1975]
gamora
```

## Індексація

Друкувати усі елементи -- це звичайно зручно, але нам буде ще потрібен механізм доступу до елементів. Іншими словами, як ми можемо роздрукувати чи замінити той чи інший елемент? Цей механізм реалізовано за допомогою індексації. Кожен елемент списку має свій індекс, за яким ми можемо його отримати. Такй собі порядковий номер.

Ви можете собі уявити це як чергу в магазині. Ви не знаєете як кого звуть, але у кожного члена цієї черги є ім'я. Ви можете спитати яке ім'я у першого, хто стоїть у черзі, або наприклад у останнього. Звичайно це буде трохи не зручно, і в реальному житті це ніхто робити не буде, але це дуже яскрава матефора яка пояснює концепт індексації. 

**Індексація у Python починається з нуля.** Це означає що перший елемент має індекс `0`, другий -- `1`, і так далі. Іншими словами, `n`-ий елемент має індекс `n - 1`. 

<!-- XXX: indexing -->

### Отримуємо елемент за його індексом

Для того, щоб отримати значення якогось елемента у списку, нам треба спершу написати ім'я цього списку, а потім його індекс у дужках. Давайте отримаємо значення найпершого елементу (індекс `0`): 

```{python}
guardians[0]
```

<!-- XXX: how to get an element -->

А тепер давайте отримаємо четвертий елемент (індекс `3`):

```{python}
guardians[3]
```

### Змінюємо елемент за його індексом

Ми також можемо змінювати елементи у списку. Для цього нам треба зазначити ім'я списка, індекс загорнутий у квадратні дужки, знак присвоєння і саме значення чи вираз: 

```{python}
guardians[3] = "Rocket Raccoon"
```

<!-- XXX: how to change an element -->

## Слайсінг (зріз)

На цьому наші пригоди з індексами не закінчуються. Будуть часи, коли вам знадобиться отримати не один елемент зі списку, а декілька. Наприклад, перші три елементи чи кожен другий елемент. Ми можемо це зробити отримаючи кожен елемент індивідуально, але у Python реалізована така крута річ, як слайсінг. 

Ідея проста -- ми записуємо ім'я змінної, і далі вираз у формі `start:stop` загорнутий у квадратні дужки. Python поверне усі елементи між індексами `start` (включно) і `stop` (виключно). Давайте отримаємо другий, третій та четветий елемент:

```{python}
guardians[1:4]
```

<!-- XXX: show how slicing works -->

Якщо ми пропутсимо `start` і зазначимо тільки `:stop`, то по замовченню Python поверне елементи починаючи з першого і до `stop`:

```{python}
guardians[:4]
```

І навпаки, якщо ми тільки зазначимо `start:` без `stop`, то Python поверне елементи починаючи з `start` і до кінця. 

```{python}
guardians[1:]
```

<!-- XXX: show how slicing works when omitting/skipping start and stop -->

Якщо ми зазначимо замість додатніх чисел від'ємні, то ми отримаємо числа з індексами відносно кінця списку: 

```{python}
guardians[-3:-1]
```

Також, ми можемо зазначити так званий `step`, або крок. Якщо ми хочемо отримати кожен другий елемент, то це буде виглядати ось так: 

```{python}
guardians[::2]
```

Будь-ласка, не забувайте пройти вправи, посилання на які ви знайдете нагорі. Слайсінг можна зрозуміти та опанувати виключно на практиці, тому не забивайте на вправи.

## Корисні оператори

Для списків, так само як і для скалярних об'єктів, ми можемо використовувати оператори. Вони дещо відрізняються за своїм призначенням, але досить інтуітивні.

### Перевіряємо чи присутній об'єкт серед елементів списку

У практиці, ви дуже часто будете користуватися опертором `in`. Він дозволяє перевірити чи міститься заданий об'єкт серед елементів списку `list`. Наприклад, чи Iron Man є одним з вартових, або іншими словами, чи міститься елемент `"Iron Man"` у списку `guardians`? Якщо так, то вираз `"Iron Man" in guardians` поверне `True`, а якщо ні -- то `False`. Давайте перевіримо:

```{python}
"Iron Man" in guardians
```

А що до `"Gamora"`?

```{python}
"Gamora" in guardians
```

Якщо ж ми хочемо переконатися, що `"Iron Man"` не є в вартових, то замість `in` ми можемо написати `not in`. Цей вираз поверне `True`, якщо `"Iron Man"` не є в вартових, або `False`, якщо є:

```{python}
"Iron Man" not in guardians
```

### З'єднуємо два списка

Їдемо далі. Якщо ми хочемо розширити список наших вартових, тобто додати ще `"Yondu Udonta"` та `"Mantis"` до `guardians`, ми можемо загорнути їх у інший `list`, та додати до `guardians`. Ще раз нагадуємо, під загорнути, ми маємо на увазі сторити новий `list`:

```{python}
["Yondu Udonta", "Mantis"]
```

А тепер додаємо цей список до нашого первинного списку `guardians`:

```{python}
guardians + ["Yondu Udonta", "Mantis"]
```

У результаті оператора `+`, ми отримали новий список, елементи якого -- це поєднання елементів першого операнда та елементів другого операнда.

### Повторємо список

Інший корисний оператор -- це `*`. Цей оператор повторює список стільки разів, скільки зазначено у другому операнді, який до речі повинен бути числом типу `int`. Наступний вираз повторить список `guardians` два рази: 

```{python}
guardians * 2
```

## Корисні функції

Для того щоб полічити кількість елементів є у списку, ми використовуємо фунцкію `len()`. У нас наразі п'ять вартових, тому наступна інструкція поверне саме `5`:

```{python}
len(guardians)
```

Для списків, елементи яких є числа корисні фунцкії `min()` та `max()`, які повертають мінімальний та максимальний елемент списку:

```{python}
some_numbers = [3, 4, 10, -3]
min(some_numbers)
max(some_numbers)
```

## Корисні методи 

Ми вже обговорювали чим методи відрізняються від функцій у главі \@ref(vars). Тут така сама історія: методи будуть модифікувати списки! Тому будьте обережні, якщо ви не хочете щоб список змінювався.

### Додаємо елементи у список

Ми вже знаємо як приєднати список до списку за допомогою оператора `+`. А ось якщо нам потрібно додати елемент до нашого списку, то ми можемо використати метод `.append()`. Він додасть новий елемент у кінець списку. Давайте додамо Mantis до нашого списку:

```{python}
guardians.append("Mantis")
guardians
```

До речі, кожного разу як ви будете виконувати новий код, ви будете додавати новий елемент `"Mantis"`. Тому будьте обережні і чітко знайте скільки разів ви виконували код.

```{python}
guardians.append("Mantis")
guardians
```

Якщо нас не влаштовує додавати новий елемент в кінец списку, ми можемо скористатися методом `.insert()`. Цей метод додає новий елемент, але ми повинні зазначити куди саме за допомогою першого агументу. Давайте додамо Yondu в перший елемент списку. Нагадуємо, індексація починається з нуля, тому перший -- значить `0`:


```{python}
guardians.insert(0, "Yondu")
guardians
```

### Видаляємо елементи зі списку

Окей, але Yodnu у певний момент не є членом команди і нам треба його видалити зі списку `guardians`. Для цього, ми будемо використовувати метод `.remove()`. Він видаляє усі елементи, які дорівнюють елементу зазначеному між дужками. Тобто якщо б ми зазначили `"Mantis"`, то `.remove()` видалив би усі елементи які дорівнюють `"Mantis"`. Але давайте спершу видалемо Yondu: 

```{python}
guardians.remove("Yondu")
guardians
```

Окей, але у нас у команді все ще дві Mantis і ми хочемо видалити тільки один елемент. Якщо ми використаємо `.remove()`, то видалемо усі `"Mantis"`. Добре що є метод `.pop()`, який видаляє елемент за його індексом. Давайте видалемо останній елемент. Який індекс відповідає останньому елементу? Мабуть ми вже й не пам'ятаємо. Але ми можемо знайти цей індекс, порахувавши за допомогою функції `len()` кількість елементів, і потім відняти один (тому що індексація починається з нуля):

```{python}
len(guardians)
```
Цей список має сім елементів, тому останній елемент має індекс `7 - 1 = 6`:

```{python}
guardians.pop(6)
guardians
```

Є ще третій спосіб видалити елемент, використовуючи ключове слово `del`. Цей метод рідко використовується, тому ми його не розглядатемемо.

### Змінюємо порядок елементів на зворотній

Іноді нам треба буде змінити порядок об'єктів, і для цього у нас є два важливих методи. Перший -- `.reverse()`, який змінює порядок елементів на зворотній:

```{python}
guardians
```

```{python}
guardians.reverse()
guardians
```

Зверніть увагу не те, що тепер `"Star Lord"` став останнім елементом, `'Gamora'` передостаннім, і так далі. 

### Сортуємо списки

Останній корисний метод, який ми розглянемо -- `.sort()`. Він сортує список в лексикографічному порядку^[Лексикографічний порядок дуже схожий на алфавітний порядок, який використовується в словниках.] (якщо елементи є об'єктами типу `str`) або у порядку зростання (якщо елементи є числовими скалярами). Давайте відсортуємо наших героїв у списку `guardians`:

```{python}
guardians.sort()
guardians
```

`"Drax"` на першому місці, тому що `D` -- це найперша літера абетки яка є в іменах героїв. На другому місці `'Gamora'` та на третьому `'Groot'`. Чому саме так? По-перше, ім'я обої героїв починається на `"G"`, тобто друга літера абетки, яка зустрічається в іменах. Щоб вирішити, хто буде на другій позиції -- ми дивимось на другу літеру імен: у `"Gamora"` -- це `a`, яка йде перед `0` у `"Groot"`. 

Тепер давайте швиденько створимо новий список з чисел:

```{python}
weather = [10, 12, 9, 9, 10, 11]
weather
```

А тепер відсортуємо його:

```{python}
weather.sort()
weather
```

До речі, якщо ми спробуємо відсортувати елементи в списку `star_lord`, то ми отримаємо помилку, тому що `.sort()` працює зі списками, елементи якого можуть бути просортовані. Ну от скажість, хто більший `'Peter Jason Quill'` чи `1976`? Не знаєте? Ось і Python не знає теж: 

```{python, error = TRUE}
star_lord.sort()
```

---
