# Словники `dict`

| Назва                 | Посилання |
|-----------------------|-----------|
| Лекція в YouTube      | https://  |
| Подкаст-лекція        | https://  |
| Код в Google Colab    | https://  |
| Вправи в Google Forms | https://  |

Слухати:

Приблизний час на опанування теми: 15 хвилин

Для чого ми це вивчаємо:

Результати навчання:

- Створювати змінні
- Використовувати та змінювати занчення змінних
- Викликати функцію та зазначати аргументи
- Використовувати математичні оператори

Шпаргалка: summarized.pdf

---

У цій главі, ми будемо вивчати чи не найважливіший контейнер. 

---

Не завжди такі послідовності як `list` та `tuple` є найзручнішими, щоб зберігати дані. Для деяких даних порядок елементів не важливий і отримувати доступ до елементів зручніше через так званий **ключ**, а не за індексом. Словники `dict` -- це як раз такий набір пар *ключ*-*значення*. Ключ, як і значення можуть бути будь-якими об'єктами у Python. Але ключі повинні бути об'єктами незмінних типів, таких як `int`, `str`, `tuple` тощо, при чому вони не повинні бути усі одного типу. З іншого боку, ключі повинні бути унікальними, тоді як значення можуть повторюватись. 


<!-- XXX: infographics on what is the dict -->

## Створюємо словник `dict`

До Балтійських країн належать Естонія, Латвія та Литва. Столицями цих країн є відповідно Талін, Ріга та Вільнюс. Якщо ми запишемо столиці до списку `list`, то ми загубимо оцей зв'язок між країною та її столицею, тому ми використаємо словник `dict`. 

Щоб створити `dict`, нам треба прописати через кому усі пари у вигляді `ключ:значення` і загорнути все це у фігурні дужки.

<!-- XXX: створюємо словник -->

Насправді, це легше ніж звучить. Давайте створимо словник `baltic_capitals` із пар країна-столиця:

```{python}
baltic_capitals = {
    "Estonia": "Tallinn",
    "Latvia": "Riga",
    "Lithuania": "Vilnius"
}
baltic_capitals
```

У цьому випадку `"Estonia"`, `"Latvia"` та `"Lithuania"` будуть ключами, за якими ми зможемо отримати значення `"Tallinn"`, `"Riga"` та `"Vilnius"`.

А ось інший прикад словника `nums`. Ключами якого є об'єкти `float`, `int` та `str`, а значення -- `str` та `list`. Цей словник не має жодного сенсу крім того, що демонструє можливості `dict`:

```{python}
nums = {
    1.1: "one point one",
    2.5: "two point 5",
    "four": [4, "four", 4.0]
}
nums
```

## Ключі

Саме цікаве починається після створення. Якщо дуже коротко, то ключі в `dict` -- це наші "нові індекси". Тобто, якщо у `list` та `tuple` нам треба було зазначити індекс у квадратних дужках, то в випадку `dict` нам треба зазначити ключ, за яким закріплена цікаве для нас значення.

### Отримуємо елемент за його ключем

Наприклад, ми хочемо дізнатися столицю Естонії. Для отримання елемента, потрібно прописати ім'я словника, і потім ключ загорнутий в квадратні дужки:

<!-- XXX: how to access elements -->

```{python}
baltic_capitals["Estonia"]
```

До речі, навпики це не працює. Якщо ми хочемо отримати країну, столиця якої `"Tallinn"`, то вираз `baltic_capitals["Tallinn"]` не спрацює (тому що у нас не існує ключа `"Tallinn"`):

```{python, error = TRUE}
baltic_capitals["Tallinn"]
```

Пам'ятаєте що ключі повинні бути унікальними? Так ось це поясняється тим, що якщо у нас було б два ключа `"Estonia"`, то Python не зміг розібратись яке саме значення повертати. 

### Змінюємо елемент за його ключем

Так само як і в `list`, ми можемо змінити елементи. Синтаксис такий самий як і у списках, але замість індексу, нам треба зазначити ключ:

<!-- XXX: how to change an element -->

```{python}
baltic_capitals["Estonia"] = "Tartu"
```

Але давайте всеж таки залишимо `"Tallinn"`, як столицю Естонії:

```{python}
baltic_capitals["Estonia"] = "Tallinn"
```

### Додаємо новий елемент з ключем

Щоб додати новий елемент до словника `dict`, ми можемо використати такий самий синтаксис, який ми використовували для змінення значень елементів: `name_of_dict[new_key] = new_value`. 

Давайте додамо Полщу до Балтійских країн (не хвилюйтеся, ми скоро її видалемо). Ключем в цій парі буде `"Poland"`, а значенням -- `"Warsaw"`.

```{python}
baltic_capitals["Poland"] = "Warsaw"
```

## Корисні оператори

На відміну від `lists`, коли ми використовуємо оператор `in`, ми перевіряємо наявність ключа, а не значення елементу. Це означає що ми можемо перевірити чи є, скажімо `"Poland"` чи `"Latvia"` серед ключей, але не можемо перевірити чи є `"Warsaw"` серед значень.

Давайте перевіримо, чи є `"Poland"` серед ключей:

```{python}
"Poland" in baltic_capitals
```

Так само як і у `list`, ми можемо використати оператор `not in`. А ось оператори `+` та `*` не реалізовані для словників `dict`.

## Корисні методи




```{python}
baltic_capitals.pop("Poland")
baltic_capitals
```

```{python}
baltic_capitals.keys()
```


```{python}
baltic_capitals.values()
```


---