# Множини `set`

<div class="btn-group">
  <button class="lecture">🎥 Лекція</button>
  <button class="podcast">🎙️ Подкаст</button>
  <button class="notebook">📓 Записник</button>
  <button class="exercises" onclick="openDetailsById('set_exercises');">🤸 Вправи</button>
  <button class="cheat">📝 Шпора</button>
</div>

**⏱️ Час на опанування теми:** 25 хвилин

**🤷 Для чого ми це вивчаємо:**

- опанувати структуру даних створену для неупорядкованих елементів
- завершити вивчення структур даних

**🔑 Результати навчання:**

- створювати множини `set`
- перевіряти чи містяться елементи у множині
- додавати та видаляти елементи
- отримувати об'єднання, перетин та різницю двох множин

---

Множина `set` -- це <span class="highlight-container"><span class="highlight">неупорядкована<span class="tooltiptext">🇬🇧 unordered</span></span></span> сукупність унікальних об'єктів. Якщо простіше -- це як `list`, але **без індексів** та тільки з **унікальними** елементами. Ми також можемо представити собі множини `set` як словники `dict`, в яких є тільки ключі 🔑 без значень. Давайте трохи зануримось у тему множин.

---

## 🧳 Створюємо множину

Пам'ятаєте як створити список `list`? Тоді ви вже майже знаєте як створити множини. Замість квадратних дужок (`[` та `]`) використайте фігурні (`{` та `}`), і це створить множину. Давайте створимо множину інгредієнтів гамбургера з МакДональдз. Це `"bun"` (булочка 🥯), `"mustard"` (гірчиця 🟡), `"ketchup"` (кетчуп 🔴), `"onion"` (цибуля 🧅), `"pickle"` (маринований огірок 🥒) та `"beef"` (яловичина 🥩):

```{python}
hamburger = {"bun", "mustard", "ketchup", "onion", "pickle", "beef"}
hamburger
```

До речі якби ми два рази зазначили `"beef"`, то словник все одно залишився б таким же. Тому що в словниках можуть бути тільки унікальні елементи, тобто без повторень. Давайте спробуємо:

```{python}
hamburger = {"bun", "mustard", "ketchup", "onion", "pickle", "beef", "beef"}
hamburger
```

До речі, як і ключі 🔑 в словниках `dict`, елементами множин `set` можуть бути тільки незмінні об'єкти, такі як `int`, `float`, `str`, `bool`, `tuple` тощо. 

Давайте ще створимо множину, яка міститиме інгредієнти МакЧікен 🍗. Нам ця множина знадобиться трохи згодом. Назвемо цей об'єкт `macchicken`: 

```{python}
macchicken = {"bun", "sauce", "salad", "chicken"}
macchicken
```

## ➕ Застосовуємо оператори

Оператори дуже важливі для множин `set` і вони є, так би мовити, основною їх фішкою. Ми почнемо вже з відомого оператора `in`, а потім перейдемо до математичних операторів.

### Перевіряємо наявність об'єкт серед елементів множини

Як і в трьох попередніх типах, множини `set` мають оператори `in` та `not in`, які дозволяють перевірити чи входить елемент в множину. Давайте перевіримо, чи є `"cheese"` (сир 🧀) серед інгредієнтів гамбургера:

```{python}
"cheese" in hamburger
```

Звичайнісінько ж ні (`False`)! Тоді б це був вже чизбургер 🍔.^[До речі, автор цієї книги є запеклим шанувальником саме чизбургерів 🍔. Він пам'ятає часи коли він навчався в школі, і чизбургери 🍔 в МакДональдз коштували 2.50 ₴.]

### Об'єднуємо множини

<span class="highlight-container"><span class="highlight">Об'єднанням<span class="tooltiptext">🇬🇧 union</span></span></span> двох множин є множина, елементами якої є елементи з обох множин. Об'єднання здійснюється за допомогою оператора `|`.

<!-- XXX: image of union -->

У нашому прикладі з бургерами, це будуть усі інгредієнти які містяться в гамбургері та усі інгредієнти які містяться в МакЧікені:

```{python}
hamburger | macchicken
```

### Знаходимо перетин множин

<span class="highlight-container"><span class="highlight">Перетин<span class="tooltiptext">🇬🇧 intersection</span></span></span> двох множин -- це ті елементи, які присутні в обох множинах. У Python він реалізований за допомогою оператора `&`.

<!-- XXX: image of intersection -->

Це ті інгредієнти, які містяться і в гамбургері і в МакЧікені (тобто тільки булочка): 

```{python}
hamburger & macchicken
```

### Знаходимо різницю між множинами

<span class="highlight-container"><span class="highlight">Різницею<span class="tooltiptext">🇬🇧 difference</span></span></span> називаються ті елементи, які входять до множини першого операнду, але **не** входять до множини другого операнда: 

<!-- XXX: image of difference -->

Різниця між `hamburger` та `macchicken`, це інгредієнти які є в гамбургері, але яких нема у МакЧікен:

```{python}
hamburger - macchicken
```

## 🪛 Застосовуємо корисні методи

Традиційно, ми почнемо з того як додавати та видаляти елементи з множини `set`. 

### Додаємо елементи до множини

Для того, щоб додати елемент до множини, ми можемо використати метод `.add()`. Новий елемент треба буде зазначити між дужками. Додаємо `"cheese"` до множини `hamburger`:

```{python}
hamburger.add("cheese")
hamburger
```

### Видаляємо елементи із множини

Так, сир не повинен бути у множині `hamburger`. Ми можемо його видалити двома методами: `.remove()` чи `.pop()`. Різниця у тому, що `.pop()` ще й поверне значення видаленого елементу, після того, як його видалить. Ми ж скористаємось `.remove()`:

```{python}
hamburger.remove("cheese")
hamburger
```

Якщо такого елемента не існує, то методи повернуть помилку: 

```{python, error = TRUE}
hamburger.remove("cheese")
```

### Методи, які еквівалентні операторам 

Математичні оператори які ми розглянули, тобто об'єднання `|`, перетин `&` та різниця `-`, також реалізовані як методи. Замість того щоб написати `a | b`, ми можемо записати цей вираз як `a.union(b)`. Цей вираз не змінить `a`, а поверне нову множину, яка дорівнюватиме `a | b`. Використовуючи множини `hamburger` та `macchicken`, маємо:

```{python}
hamburger.union(macchicken)
```

Нижче ми покажемо таблицю відповідності методів до операторів: 

|  Оператор  |  Метод              |
|------------|---------------------|
| `a | b`    | `a.union(b)`        |
| `a & b`    | `a.intersection(b)` |
| `a - b`    | `a.difference(b)`   |

---

Йой, ти взагалі розумієш, що зараз сталося? Ми не просто навчились тільки що створювати множини `set` та працювати з їх елементами. Ні! Опанувавши множини `set`, ми звершили величезний блок зі структур даних 😎 Це велика перемога 👏, і тепер головне не зупинятись! 

---

<details id="set_exercises">
<summary>🤸 Вправи</summary>

  <div class="quiz">
  <div class="question">1\. Як створити множину?</div>
  <label><input type="radio" name="create" value="false"> `x = [1, 2, 3]` </label>
  <label><input type="radio" name="create" value="false"> `x = (1, 2, 3)` </label>
  <label><input type="radio" name="create" value="true"> `x = {1, 2, 3}`</label>
  <button class="check" id="check-btn" onclick="checkAnswer('check-btn', 'create');" disabled>Перевірити</button>
  </div>
  
```{r, results='asis', message=FALSE, echo=FALSE}
jsquiz::generate_mcq(
    question = "2. Виберіть мову програмування:",
    answers = c(
        "Python" = TRUE,
        "C++" = TRUE,
        "RStudio" = FALSE
    ),
    button_label = "Перевірити",
    allow_multiple_answers = TRUE,
    button_id = "check_set_2",
    radio_buttons_id = "mcq_set_2"
)
```

</details>
