# Працюємо із текстовими стрічками {#string}

## Багаторядкові текстові стрічки

Стрічки можуть займати також кілька рядків. Щоб створити стрічку з декількох рядків, ми можемо використати три одинарні або три подвійні лапки:

```{python}
poem = """Реве та стогне Дніпр широкий,
Сердитий вітер завива...
"""

poem
```

Скоріш за все, ви звернули увагу, що замість нового рядку, Python видав комбінацію символів `\n`. Ця комбінація має спеціальний зміст, а саме -- нова строка. 

## Спеціальні та керуючі символи

Символ `\` (backslash) використовується як символ "виходу" (escape character) -- символ після `/` буде інтерпертуватись по іншому. Наприклад, `\n` означає новий рядок, `\t` означає табуляцію.

## Оператори 

```{python}
part1 = "Hey! "
part2 = "How are you doing?"

part1 + part2
```

```{python}
phraze = "Я не повторюю два рази! "

phraze * 2
```

## Довжина текстової стрічки

```{python}
address = "221B Baker Street"
len(address)
```

## Індексація та слайсінг

Те, що ми використовували для `list` та `tuples` (Глава XXX та XXX), можна використовувати й тут.

```{python}
address = "221B Baker Street"
address[3]
```

Але на відміну від list, наприклад, ми не можемо змінити стрічку. 

```{python, error = TRUE}
address = "221B Baker Street"
address[3] = "A"
```

Проте, є все одно один маленький трюк -- метод `.replace()`, про який ми поговоримо у секції \@ref(string-methods).

Слайсінг або зріз.

```{python}
address = "221B Baker Street"
address[0:4]
```


<!-- Подумай чи має сенс додавати це сюди? -->

## Корисні методи стрічок {#string-methods}


```{python}
address = "221B Baker Street"
address.replace("221B", "222")
```

```{python}
address = "221B Baker Street"
address.split(" ")
```

```{python}
address = "221B Baker Street"
address.upper()
```