# (PART\*) Навички {-}

# Що робити коли код не працює?

| Назва                 | Посилання |
|-----------------------|-----------|
| Лекція в YouTube      | https://  |
| Подкаст-лекція        | https://  |
| Код в Google Colab    | https://  |
| Вправи в Google Forms | https://  |

Слухати:

Приблизний час на опанування теми: 15 хвилин

Для чого ми це вивчаємо:

Результати навчання:

- Розуміння що таке програма, додаток та програмне забезпечення
- Розуміння що таке алгоритм, кодування та програмування 

Шпаргалка: summarized.pdf

---

У цій главі...

---

Ви колись замислювались, як ви навчились ходити? Напевно, це був процес навчання, спочатку ви навчились повзати, потім ви почали по тихеньку підводитись, зробили свій перший крок, через якісь час другий. І сто відсотків за весь час вашого навчання ви падали величезну кількість разів. Якщо вам цікава статистика, то малюки від 12 до 19 років падають 17 разів. На годину!

Так і в програмуванні, якщо ви робили будь-які вправи, то ви напевно робили десь помилку, чи у певний помент ваш код не працював. І це абсолютно нормальний процес. Помилятися -- невідємна частина начання. Але по-перше, такі помилки у коді можуть дуже засмучувати, а по-друге, навчання здійснюється саме тоді, коли ці помилки виправляються. Ну і звичайно, коли ви будете працювати програмістом, вам треба буде навчитись виправляти помилки. Коли ви знаєте що у вас в коді є помилка і намагаєтесь її виправити -- це називається debugging або налагодження.

З іншого боку, інколи (або якщо чесно то дуже часто) у вас будуть питання як саме вирішити ту чи іншу проблему. Наприклад, ви не знаєте яка функція розділяє стрічку на декілька підстрічок використовуючи певний розділювальний символ (delimiter) або як знайти суму виключно від'ємних чисел у списку чи масиві.

Для цих вищезазначених випадків ми розглянемо алгоритм дій.

<!-- XXX: flowchart of workflow if something does not work -->

## Питаємо у ChatGPT...

Якщо б ця книга була написана до 2022 року, то цей пункт не існував би. Але усе повністю змінилось коли OpenAI представили свого нового помічника ChatGPT, який базується на штучному інтелекті. На початку вашого шляху у програмуванні це буде ваш найліпший друг і зараз ми навчимося їм користуватись. 

ChatGPT розуміє українську, хоч українська і не рідна мова для ChatGPT. Це означає що ми можемо формулювати усі свої питання українською.

### ...як розв'язати певну задачу?

Якщо ми хочемо запитати у ChatGPT як розв'язати певну задачу, ми можемо використати кілька правил, які зроблять запит максимально ефективним. Ми почнемо з максимально розмитого запиту і з кожним кроком будемо його вдосконалювати.

Наприклад, нам потрібно розбити стрічку `"Привіт! Як справи?"` на `"Привіт!"`, `"Як"` та `"справи?"`. Ми почнемо з запиту: 

> Як розділити текст?

І це нажаль не спрацює.

* Треба бути точними і надати як найомога більше деталей

    Попередній запит нажаль не дуже зрозумілий для ChatGPT тому що він не розуміє конексту -- ми говоримо про літературні тексти чи про тексти в мовах програмування? Щоб покращити цей запит, ми можемо конретизувати про що саме йде мова:
    
    > Як розділити текстову стрічку на частини?
    
    А ще краще конкретизувати як саме ми хочемо розділити. Розділити ми повинні за допомогою символу пробілу, тому ми можемо ще раз переписати наш запит: 
    
    > Як розділити текстову стрічку на частини за допомогою символу? 

* Треба використовувати Python терміни

    Щоб зробити конекст ще більше зрозумілим, нам потрібно використати терміни, якими оперує Python. У нашому прикладі, замість **текстову стрічку** ми можемо викоритати **стрічка str**:
    
    > Як розділити стрічку str на частини за допомогою символу?

* Треба додати **y Python**
    
    Якщо ж ChatGPT все ж таки й досі не зрозумів що ми працюємо у Python, ми можемо це явно прописати у нашому запиті: 
    
    > Як розділити стрічку str на частини за допомогою символу y Python?

### ...виправити помилку?

Нижче зазначенний код видає помилку:

```{python, error = TRUE}
question = "The Answer to the Ultimate Question of Life, the Universe, and Everything is"

answer = 42

question + answer
```

ChatGPT може нам допомогти її випаравити. Для цього треба прописати запит: 

> Як виправити цю помилку у Python?

І додати з нової строки код та текст повідомлення помилки: 

> Як виправити цю помилку у Python?
> question = "The Answer to the Ultimate Question of Life, the Universe, and Everything is"
> answer = 42
> TypeError: can only concatenate str (not "int") to str

Якщо помилку видає виклик функції, яку ви написали самі, то треба разом із викликом фунцкії також надати і код визначення фунцкії.


## Що таке налагодження (debugging)?

## Як подивитись документацію? 

## Як написати запит у Google?

## Що таке Stackoverflow? 

## Як використати ChatGPT?
