# Шукаємо інформацію в Інтернеті

<div class="btn-group" style="width:100%">
  <button style="width:20%; background-color: #ed6a5d">🎥 Лекція</button>
  <button style="width:20%; background-color: #f5be4f">🎙️ Подкаст</button>
  <button style="width:20%; background-color: #61c554">📓 Записник</button>
  <button style="width:20%; background-color: #6db2d6">🤸 Вправи</button>
  <button style="width:20%; background-color: #a38ebd">📝 Шпора</button>
</div>

**⏱️ Час на опанування теми:** 15 хвилин

**🤷 Для чого ми це вивчаємо:**

**🔑 Результати навчання:**

- Розуміння що таке програма, додаток та програмне забезпечення
- Розуміння що таке алгоритм, кодування та програмування 

---

Інколи (або якщо чесно то дуже часто) у вас будуть питання як саме вирішити ту чи іншу проблему. Наприклад, ви не знаєте яка функція розділяє стрічку на декілька підстрічок використовуючи певний розділювальний символ (delimiter) або як знайти суму виключно від'ємних чисел у списку чи масиві. Також, будуть такі випадки, коли ви не зможете самостійно знайти помилку у коді. Для цих сценаріїв ми навичмося шукати інформацію в інтернеті.

---

Спочатку ми обговоримо яка саме послідовність методів є найефективнішою (принайні з досвіду автора). Почати, як це не парадоксально, якнайкраще з найсучаснішої технології -- ChatGPT. Якщо це не спрацює, треба буде засукати рукава і почати ретельно шукати у Google. Якщо ж ви не знайдете і там або на Stack Overflow, наступним кроком буде самостійно поставити питання на Stack Overflow. І останнім, але не меньш важливим ресурсом є офіційна документація.

<!-- XXX: flowchart of workflow if something does not work -->

## Питаємо у ChatGPT...

Якщо б ця книга була написана до 2022 року, то цей пункт не існував би. Але усе повністю змінилось коли OpenAI представили свого нового помічника ChatGPT, який базується на штучному інтелекті. На початку вашого шляху у програмуванні це буде ваш найліпший друг і зараз ми навчимося їм користуватись. 
ChatGPT розуміє українську, хоч українська і не рідна мова для ChatGPT. Це означає що ми можемо формулювати усі свої питання українською.

### ...як розв'язати певну задачу?

Якщо ми хочемо запитати у ChatGPT як розв'язати певну задачу, ми можемо використати кілька правил, які зроблять запит максимально ефективним. Ми почнемо з максимально розмитого запиту і з кожним кроком будемо його вдосконалювати.

Наприклад, нам потрібно розбити стрічку `"Привіт! Як справи?"` на `"Привіт!"`, `"Як"` та `"справи?"`. Ми почнемо з запиту: 

> Як розділити текст?

І це нажаль не спрацює.

* Треба бути точними і надати як найомога більше деталей

    Попередній запит нажаль не дуже зрозумілий для ChatGPT тому що він не розуміє конексту -- ми говоримо про літературні тексти чи про тексти в мовах програмування? Щоб покращити цей запит, ми можемо конретизувати про що саме йде мова:
    
    > Як розділити текстову стрічку на частини?
    
    А ще краще конкретизувати як саме ми хочемо розділити. Розділити ми повинні за допомогою символу пробілу, тому ми можемо ще раз переписати наш запит: 
    
    > Як розділити текстову стрічку на частини за допомогою символу? 

* Треба використовувати Python терміни

    Щоб зробити конекст ще більше зрозумілим, нам потрібно використати терміни, якими оперує Python. У нашому прикладі, замість **текстову стрічку** ми можемо викоритати **стрічка str**:
    
    > Як розділити стрічку str на частини за допомогою символу?

* Треба додати **y Python**
    
    Якщо ж ChatGPT все ж таки й досі не зрозумів що ми працюємо у Python, ми можемо це явно прописати у нашому запиті: 
    
    > Як розділити стрічку str на частини за допомогою символу y Python?
    
І ось такою приблизно буде відповідь ChatGPT: 

<!-- XXX: output of ChatGPT -->

Ми можемо просто скопіювати код і виконати його: 

```{python}
greeting = "Привіт! Як справи?"
greeting.split(" ")
```

### ...виправити помилку?

Нижче зазначенний код видає помилку:

```{python, error = TRUE}
question = "The Answer to the Ultimate Question of Life, the Universe, and Everything is "

answer = 42

question + answer
```

ChatGPT може нам допомогти її випаравити. Для цього треба прописати запит: 

> Як виправити цю помилку у Python?

І додати з нової строки код та текст повідомлення помилки: 

> Як виправити цю помилку у Python?
> question = "The Answer to the Ultimate Question of Life, the Universe, and Everything is"
> answer = 42
> TypeError: can only concatenate str (not "int") to str

Приблизно ось так відповість ChatGPT: 

<!-- XXX: output of ChatGPT -->

Це означає що нам треба було просто загорнути `answer` у `str()`:

```{python, error = TRUE}
question = "The Answer to the Ultimate Question of Life, the Universe, and Everything is "

answer = 42

question + str(answer)
```

Якщо помилку видає виклик функції, яку ви написали самі, то треба разом із викликом фунцкії також надати і код визначення фунцкії.

Ось клітинка з визначенням фунцкії:

```{python}
def standardize(x):
    return (x - mean) / sd
```

А ось виклик, який генерує помилку: 

```{python, error = TRUE}
standardize(0.032, 0, 1)
```

Нам треба передати ось такий запит: 

> Чому наступний код генерує помилку: 
> def standardize(x):
> return (x - mean) / sd
> standardize(0.032, 1, 0)
> TypeError: standardize() takes 1 positional argument but 3 were given

ChatGPT відповість щось накшталт: 

<!-- XXX: output of ChatGPT -->

Це означає що ми забули зазначити ще два параметри `mean` та `sd` у визначенні функції: 

```{python}
def standardize(x, mean, sd):
    return (x - mean) / sd

standardize(0.032, 0, 1)
```

Далі ми розглянемо більш олд-скульні метроди знаходження інформації, які використовувались в епоху коли ChatGPT ще не існував. 

## Google

Google -- це назамінний помічник у пошуку інформації, і програмування тут не є виключенням. Ми можемо його використовувати і для пошуку вирішення помилки у коді і для того щоб знайти вирішення певної задачі. Шукати у Google є навичкою яку можна здобути тільки з практикою. В процесі пошуку дуже важлвиво не зупинятись на першій спробі, а декілька разів змінити запит і подивитись що саме запропонує Google.

Хоча рекомендації до використання Google й схожі на рекомендації для ChatGPT, все ж таки існує кілька відмінностей:

- Запити краще формулювати на англійській мові. Якщо у вас є труднощі з цим, ви завжди можете перекласти з україньскої на англійську за допомогою Google Translate. Замість: 

    > Як розбити стрічку у Python? 

    Крщае запитати: 

    > How to split a string in Python?

- Якщо у ChatGPT краще надавати якомога більше інформації, то у Google краще навпаки надати тільки кілька ключових слів. Замість:

    > How to split a string in Python?

    Краще запитати: 
    
    > split string Python 
    
    Найкраще, якщо ці слова будуть термінами з Python.

- Якщо ви шукаєте як виправити помилку, то найефективнішою стратегією буде сформувати запит з повідомлення цієї помилки. Якщо повідомлення містить будь-які артефакти причетні тільки до вашого комп'ютеру чи коду, то їх краще прибрати. Наприклад, такі штуки як шляхи до файлів, назви змінних тощо. Код нижче читає файл, якого не існує: 

    ```{python, error = TRUE}
    f = open("file_that_does_not_exist.txt", "r")
    print(f.read())
    ```
    
    Тоді найкращий запит буде виглядати (у ньому ми прибрали ім'я файлу): 
    
    > FileNotFoundError: [Errno 2] No such file or directory:

## Stack Overflow

Stack Overflow -- популярна система питань і відповідей стосовно програмування. Є така приказка, що питання на яке ви шукаєте відповідь, вже хтось колись задавав на Stack Overflow. З досвіду автора цієї книги це не дуже далеко від правди.

Коли ви використовуєте Google для пошуку, він часто пропонує сторінки на Stack Overflow і це практично сто-відсоткове попадання, тому це треба мати на увазі. 

Але буває таке, що ми не можемо знайти відповідь на наше питання, і тоді краще зареєструватись на Stack Overflow і задати питання власноруч. Ми не будемо описувати процес написання питання, так як якщо вам потрібно задати таке питання, то скоріш всього ви на тому рівні, де опанувати Stack Overflow для вас не буде проблемаю. По-друге, Stack Overflow має дуже зрозумілий набір інструкцій, який допоможе вам з цим.

## Вбудована документація

Ще одине важлививе джерело інформацій -- вбудована документація. Для того щоб побачити документацію якоїсь фунцкції, нам треба сформувати існтрукцію `help(name_of_function)`, де `name_of_function` -- ім'я функції без дужок:

```{python}
help(len)
```

Ми так само можемо подивитись документацію методів об'єктів: 

```{python}
x = "a string"
help(x.split)
```

Офіціфну документацію тако ж можна знайти на сайті (https://docs.python.org/3/)[https://docs.python.org/3/]. 
