# Просунута індексація {#advanced-index}

## Відємна індексація

## Зрізи

### `start` та `stop` за замовчуванням

```{python}
guardians = ["Star Lord", "Gamora", "Drax", "Rocket", "Groot"]
```

Якщо ми пропустимо `start` і зазначимо тільки `:stop`, то `r term("за замовчуванням", "by default")` Python поверне елементи починаючи з самого початку і до `stop` (виключно). Ми будемо багато використовувати термін "за замовчуванням". Це означає що якщо ми не зазначимо певний параметр, то значення цього параметру автоматично прийме певне значення, яке передбаченне розробниками. У нашому випадку, параметр `start` за замовчуванням має значення `0`.

```{python}
guardians[:4]
```

І навпаки, якщо ми тільки зазначимо `start:` без `stop`, то Python поверне елементи починаючи з `start` і до самого кінця. За замовчуванням, `stop` дорівнює довжині списку:

```{python}
guardians[2:]
```

<!-- XXX: show how slicing works when omitting/skipping start and stop -->

### Use-case: перша половина списку та друга половина списку

```{python}
guardians[:4] # first 4 elements
guardians[4:] # the rest
```

### Від'ємні `start` та `stop`

Якщо ми зазначимо замість додатних чисел від'ємні, то ми отримаємо числа з індексами відносно кінця списку: 

```{python}
guardians[-3:-1]
```

<!-- XXX: show how slicing works when omitting/skipping start and stop -->

### Крок `step`

Також, ми можемо зазначити так званий `step`, або крок. Якщо ми хочемо отримати кожен другий елемент, то це буде виглядати ось так: 

```{python}
guardians[::2]
```
